#!/bin/sh

#xrdb $HOME/.Xresources
xsetroot -solid grey

#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &

export XKL_XMODMAP_DISABLE=1
autocutsel -fork
openbox &
/usr/bin/lxsession -s Lubuntu -e LXDE &

# https://ubuntuforums.org/showthread.php?t=2193100
